config/routes.rb
Rails.application.routes.draw do
devise_for :users, :controllers => { :omniauth_callbacks => "users/omniauth_callbacks" }

# devise_scope :user do
# delete 'sign_out', :to => 'devise/sessions#destroy', :as => :destroy_user_session
# end

  root "images#index"
  # devise_for :users
  resources :images do
    resources :comments
  end

  resources :images do
    resources :likes
  end
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
class Comment < ApplicationRecord
  has_many :users
  belongs_to :image
end

app/models/image.rb
class Image < ActiveRecord::Base
  has_many :comments, dependent: :destroy
  has_many :users
  has_many :comments
  has_many :likes
  validates :name, length: { minimum: 3 }, uniqueness: true



  has_attached_file :image, :styles => { :medium => "300x300>", :thumb => "100x100>" }, :default_url => "/images/:style/missing.png"
  validates_attachment_content_type :image, :content_type => /\Aimage\/.*\Z/

end

app/models/like.rb
class Like < ApplicationRecord
  belongs_to :image
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable,
         :omniauthable, :omniauth_providers => [:facebook]

  has_many :images
  has_many :comments
  has_many :comments_images, through: :comments, source: :image
  validates :email, uniqueness: true



  def self.from_omniauth(auth)
    where(provider: auth.provider, uid: auth.uid).first_or_create do |user|
      user.email = auth.info.email
      user.password = Devise.friendly_token[0,20]
    end
  end

  def self.new_with_session(params, session)
    super.tap do |user|
      if data = session["devise.facebook_data"] && session["devise.facebook_data"]["extra"]["raw_info"]
        user.email = data["email"] if user.email.blank?
      end
    end
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController

  def new
    @image = Image.find(params[:image_id])
    @comment = Comment.new
  end

  def create
  @image = Image.find(params[:image_id])
  @image.comments.create(review_params)
  redirect_to '/images'
end

private

def review_params
  params.require(:comment).permit(:comments)
end
end

app/controllers/images_controller.rb
class ImagesController < ApplicationController
  before_action :set_image, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!, :except => [:index, :show]
  # GET /images
  # GET /images.json
  def index
    @images = Image.all
  end

  # GET /images/1
  # GET /images/1.json
  def show
    @comments = Comment.where(:image_id => params[:id])
  end

  # GET /images/new
  def new
    @image = Image.new
  end

  # GET /images/1/edit
  def edit
  end

  # POST /images
  # POST /images.json
  def create
    @image = Image.new(name: image_params["name"], picture: image_params["picture"], image_file_name:image_params["image_file_name"], user_id: current_user.id)
      if @image.save
        redirect_to images_path
      else
        render 'new'
      end
  end

  # PATCH/PUT /images/1
  # PATCH/PUT /images/1.json
  def update
    @image.update(image_params)
    redirect_to '/images'
  end

  # DELETE /images/1
  # DELETE /images/1.json
  def destroy
    @image = Image.find(params[:id])
    @image.destroy
    flash[:notice] = "Image successfully deleted"
    redirect_to '/images'

  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_image
      @image = Image.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def image_params
      params.require(:image).permit(:name, :picture, :image)
    end
end

app/controllers/likes_controller.rb
class LikesController < ApplicationController
  def create
    @image = Image.find(params[:image_id])
    @image.likes.create
    render json: {new_like_count: @image.likes.count}
  end
end

app/controllers/users/omniauth_callbacks_controller.rb
class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController

  def facebook
      # You need to implement the method below in your model (e.g. app/models/user.rb)
      @user = User.from_omniauth(request.env["omniauth.auth"])

      if @user.persisted?
        sign_in_and_redirect @user, :event => :authentication #this will throw if @user is not activated
        set_flash_message(:notice, :success, :kind => "Facebook") if is_navigational_format?
      else
        session["devise.facebook_data"] = request.env["omniauth.auth"]
        redirect_to new_user_registration_url
      end
    end

    def failure
      redirect_to root_path
    end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/images_helper.rb
module ImagesHelper
end

app/helpers/likes_helper.rb
module LikesHelper
end

app/views/comments/new.html.erb
<%= form_for [@image, @comment] do |f| %>
  <%= f.label :comments %>
  <%= f.text_area :comments %>
  <%= f.submit 'Post Comment' %>
<% end %>

app/views/images/_form.html.erb
<%= form_for @image, html: {multipart: true} do |f| %>
  <% if image.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(image.errors.count, "error") %> prohibited this image from being saved:</h2>

      <ul>
      <% image.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
  <%= f.file_field :image, accept: 'image/jpeg,image/gif/image/png' %>
  </div>

  <div class="field">
    <%= f.label :name %>
    <%= f.text_field :name %>
  </div>

  <div class="field">
    <%= f.label :picture %>
    <%= f.text_field :picture %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/images/edit.html.erb
<h1>Editing Image</h1>

<%= render 'form', image: @image %>

<%= link_to 'Show', @image %> |
<%= link_to 'Back', images_path %>

app/views/images/index.html.erb
<p id="notice"><%= notice %></p>
<div class="center">
<h1>Welcome to Snapshot</h1>
</div>
  <body>
  <% if user_signed_in? %>
    <!-- <p><%= link_to 'Add new Image', new_image_path %></p> -->

      <% if @images.any? %>
      <ul>
          <% @images.each do |image| %>
              <% if user_signed_in? %>
              <li>
                <%= image.name %>
                <%= image.picture %>
                <%= image_tag image.image.url(:thumb) %>
                <%= link_to "View", image %>
                <%= link_to "like", image_likes_path(image), class: 'likes-link' %>
                <span class='likes_count'><%= image.likes.count%> </span>
                <%= link_to "Comment", new_image_comment_path(image) %>
                  <% if current_user.id == image.user_id %>
                    <%= link_to "Edit", edit_image_path(image) %>
                    <%= link_to "Delete", image, method: :delete %>
                  <% end %>
              </li>

            <% end %>
          <% end %>
      <% else %>
      <h1>No images yet</h1>
      <% end %>
    </ul>
  <% end %>
</body>

app/views/images/new.html.erb
<h1>New Image</h1>

<% if @image.errors.any? %>
  <section id="errors" >
    <h2> <%= pluralize(@image.errors.count, "error") %> prohibited this image from being saved: </h2>
    <ul>
      <% @image.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </section>
<% end %>

<%= render 'form', image: @image %>

<%= link_to 'Back', images_path %>

app/views/images/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @image.name %>
</p>

<p>
  <strong>Picture:</strong>
  <%= @image.picture %>
</p>
<p>
  <% if @comments.any? %>
      <% @comments.each do |comment| %>
        <%= comment.comments %>
      <% end %>
  <% end %>
</p>


<%= link_to 'Back', images_path %>

app/views/layouts/_navigation.html.erb
<nav class="navbar navbar-default">
  <div class="container-fluid">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <!-- <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button> -->
      <% if user_signed_in? %>
      <a class="navbar-brand" id="logo">Welcome <%= current_user.email %></a><br>
      <% end %>
      <% if user_signed_in? %>
        <a><%= link_to "Sign out", destroy_user_session_path, class: "navbar-brand", id: "logo", method: :delete %></a>
        <a><%= link_to 'Add new Image', new_image_path, class: "navbar-brand", id: "logo" %></a>
<% else %>
      <a><%= link_to "Sign in with Facebook", user_facebook_omniauth_authorize_path, class: "navbar-brand", id: "logo" %></a>
      <a><%= link_to "Sign in", new_user_session_path, class: "navbar-brand", id: "logo"  %></a>
      <a><%= link_to "Sign up", new_user_registration_path, class: "navbar-brand", id: "logo"  %></a>
      <% end %>
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <!-- <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav"> -->


        <!-- <li><a href="#">Link</a></li>
        <li><%= link_to 'Add new Image', new_image_path %></li>
        <li class="dropdown">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Dropdown <span class="caret"></span></a>
          <ul class="dropdown-menu">
            <li><a href="#">Action</a></li>
            <li><a href="#">Another action</a></li>
            <li><a href="#">Something else here</a></li>
            <li role="separator" class="divider"></li>
            <li><a href="#">Separated link</a></li>
            <li role="separator" class="divider"></li>
            <li><a href="#">One more separated link</a></li>
          </ul>
        </li>
      </ul> -->
      <!-- <form class="navbar-form navbar-left">
        <div class="form-group">
          <input type="text" class="form-control" placeholder="Search">
        </div>
        <button type="submit" class="btn btn-default">Submit</button>
      </form> -->
      <!-- <ul id='logo' class="nav navbar-nav navbar-right">
          <li><%= link_to 'Add new Image', new_image_path %></li>
          </ul>
        </li>
      </ul>
    </div>
  </div> -->
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>InstagramChallenge</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <!-- <% if user_signed_in? %>
    Welcome <%= current_user.email %><br>
    <% end %>
    <% if user_signed_in? %>
      <%= link_to "Sign out", destroy_user_session_path, method: :delete %>
    <% else %>
      <%= link_to "Sign in with Facebook", user_facebook_omniauth_authorize_path %>
      <%= link_to "Sign in", new_user_session_path %>
      <%= link_to "Sign up", new_user_registration_path %>
    <% end %> -->
    <%= render 'layouts/navigation' %>
    <div class="container">
    <%= yield %>
  </div>
  </body>
</html>